const INGEST_INTERVAL = process.env.INGEST_INTERVAL_MS || 300000;
const SYNC_BASE_URL = process.env.SYNC_BASE_URL || 'https://api.valvas.info';
const SYNC_FILES_PATH = process.env.SYNC_FILES_PATH || '/deltas';
const SYNC_FILES_ENDPOINT = `${SYNC_BASE_URL}${SYNC_FILES_PATH}`;
const DOWNLOAD_FILE_PATH = process.env.DOWNLOAD_FILE_PATH || '/files/:id/download';
const DOWNLOAD_FILE_ENDPOINT = `${SYNC_BASE_URL}${DOWNLOAD_FILE_PATH}`;

export {
  INGEST_INTERVAL,
  SYNC_BASE_URL,
  SYNC_FILES_ENDPOINT,
  DOWNLOAD_FILE_ENDPOINT
}